// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DemoTokenProgram;

impl DemoTokenProgram {
    pub const ROUTE_ID_VFT: u8 = 1;
    pub const ROUTE_ID_ADMIN: u8 = 2;
    pub const ROUTE_ID_FAUCET: u8 = 3;
}

impl sails_rs::client::Program for DemoTokenProgram {}

pub trait DemoToken {
    type Env: sails_rs::client::GearEnv;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env>;
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env>;
    fn faucet(&self) -> sails_rs::client::Service<faucet::FaucetImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DemoToken for sails_rs::client::Actor<DemoTokenProgram, E> {
    type Env = E;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env> {
        self.service(DemoTokenProgram::ROUTE_ID_VFT)
    }
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env> {
        self.service(DemoTokenProgram::ROUTE_ID_ADMIN)
    }
    fn faucet(&self) -> sails_rs::client::Service<faucet::FaucetImpl, Self::Env> {
        self.service(DemoTokenProgram::ROUTE_ID_FAUCET)
    }
}
pub trait DemoTokenCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
        faucet_amount: U256,
        faucet_cooldown_secs: u64,
    ) -> sails_rs::client::PendingCtor<DemoTokenProgram, io::New, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DemoTokenCtors
    for sails_rs::client::Deployment<DemoTokenProgram, E>
{
    type Env = E;
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
        faucet_amount: U256,
        faucet_cooldown_secs: u64,
    ) -> sails_rs::client::PendingCtor<DemoTokenProgram, io::New, Self::Env> {
        self.pending_ctor((name, symbol, decimals, faucet_amount, faucet_cooldown_secs))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (name: String, symbol: String, decimals: u8, faucet_amount: U256, faucet_cooldown_secs: u64) -> (), 0);
}

pub mod vft {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum TokenError {
        Paused,
        ZeroAddress,
        ZeroAmount,
        InsufficientBalance,
        InsufficientAllowance,
        Unauthorized,
        Overflow,
        FaucetDisabled,
        FaucetCooldown { next_claim_at: u64 },
    }

    pub trait Vft {
        type Env: sails_rs::client::GearEnv;
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env>;
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env>;
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env>;
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
    }

    pub struct VftImpl;

    impl sails_rs::client::Identifiable for VftImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([105, 76, 176, 174, 66, 102, 215, 121]);
    }

    impl<E: sails_rs::client::GearEnv> Vft for sails_rs::client::Service<VftImpl, E> {
        type Env = E;
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env> {
            self.pending_call((owner, spender))
        }
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((spender, value))
        }
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((account,))
        }
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env> {
            self.pending_call(())
        }
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env> {
            self.pending_call((to, value))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, value))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Allowance (owner: ActorId, spender: ActorId) -> U256, 0, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Approve (spender: ActorId, value: U256) -> bool | super::TokenError, 1, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(BalanceOf (account: ActorId) -> U256, 2, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Decimals () -> u8, 3, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Name () -> String, 4, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Symbol () -> String, 5, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TotalSupply () -> U256, 6, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Transfer (to: ActorId, value: U256) -> bool | super::TokenError, 7, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, value: U256) -> bool | super::TokenError, 8, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum VftEvents {
            #[codec(index = 0)]
            Approval {
                owner: ActorId,
                spender: ActorId,
                value: U256,
            },
            #[codec(index = 1)]
            Transfer {
                from: ActorId,
                to: ActorId,
                value: U256,
            },
        }

        impl VftEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Approval { .. } => 0,
                    Self::Transfer { .. } => 1,
                }
            }
        }

        impl sails_rs::client::Event for VftEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for VftEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for VftImpl {
            type Event = VftEvents;
        }
    }
}

pub mod admin {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum TokenError {
        Paused,
        ZeroAddress,
        ZeroAmount,
        InsufficientBalance,
        InsufficientAllowance,
        Unauthorized,
        Overflow,
        FaucetDisabled,
        FaucetCooldown { next_claim_at: u64 },
    }

    pub trait Admin {
        type Env: sails_rs::client::GearEnv;
        fn admin_account(&self) -> sails_rs::client::PendingCall<io::AdminAccount, Self::Env>;
        fn burn(
            &mut self,
            from: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env>;
        fn grant_minter(
            &mut self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinter, Self::Env>;
        fn is_minter(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsMinter, Self::Env>;
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env>;
        fn mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env>;
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env>;
        fn revoke_minter(
            &mut self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinter, Self::Env>;
        fn set_faucet(
            &mut self,
            amount: U256,
            cooldown_secs: u64,
        ) -> sails_rs::client::PendingCall<io::SetFaucet, Self::Env>;
        fn transfer_admin(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env>;
    }

    pub struct AdminImpl;

    impl sails_rs::client::Identifiable for AdminImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([53, 194, 217, 141, 188, 185, 24, 237]);
    }

    impl<E: sails_rs::client::GearEnv> Admin for sails_rs::client::Service<AdminImpl, E> {
        type Env = E;
        fn admin_account(&self) -> sails_rs::client::PendingCall<io::AdminAccount, Self::Env> {
            self.pending_call(())
        }
        fn burn(
            &mut self,
            from: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env> {
            self.pending_call((from, value))
        }
        fn grant_minter(
            &mut self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinter, Self::Env> {
            self.pending_call((account,))
        }
        fn is_minter(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsMinter, Self::Env> {
            self.pending_call((account,))
        }
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env> {
            self.pending_call(())
        }
        fn mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env> {
            self.pending_call((to, value))
        }
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env> {
            self.pending_call(())
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env> {
            self.pending_call(())
        }
        fn revoke_minter(
            &mut self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinter, Self::Env> {
            self.pending_call((account,))
        }
        fn set_faucet(
            &mut self,
            amount: U256,
            cooldown_secs: u64,
        ) -> sails_rs::client::PendingCall<io::SetFaucet, Self::Env> {
            self.pending_call((amount, cooldown_secs))
        }
        fn transfer_admin(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env> {
            self.pending_call((to,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AdminAccount () -> ActorId, 0, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Burn (from: ActorId, value: U256) -> bool | super::TokenError, 1, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GrantMinter (account: ActorId) -> bool | super::TokenError, 2, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsMinter (account: ActorId) -> bool, 3, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsPaused () -> bool, 4, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Mint (to: ActorId, value: U256) -> bool | super::TokenError, 5, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Minters () -> Vec<ActorId>, 6, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Pause () -> bool | super::TokenError, 7, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Resume () -> bool | super::TokenError, 8, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RevokeMinter (account: ActorId) -> bool | super::TokenError, 9, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetFaucet (amount: U256, cooldown_secs: u64) -> bool | super::TokenError, 10, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TransferAdmin (to: ActorId) -> bool | super::TokenError, 11, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum AdminEvents {
            #[codec(index = 0)]
            AdminTransferred { from: ActorId, to: ActorId },
            #[codec(index = 1)]
            Burned { from: ActorId, value: U256 },
            #[codec(index = 2)]
            FaucetConfigured { amount: U256, cooldown_secs: u64 },
            #[codec(index = 3)]
            Minted { to: ActorId, value: U256 },
            #[codec(index = 4)]
            MinterGranted { account: ActorId },
            #[codec(index = 5)]
            MinterRevoked { account: ActorId },
            #[codec(index = 6)]
            Paused { by: ActorId },
            #[codec(index = 7)]
            Resumed { by: ActorId },
        }

        impl AdminEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::AdminTransferred { .. } => 0,
                    Self::Burned { .. } => 1,
                    Self::FaucetConfigured { .. } => 2,
                    Self::Minted { .. } => 3,
                    Self::MinterGranted { .. } => 4,
                    Self::MinterRevoked { .. } => 5,
                    Self::Paused { .. } => 6,
                    Self::Resumed { .. } => 7,
                }
            }
        }

        impl sails_rs::client::Event for AdminEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for AdminEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for AdminImpl {
            type Event = AdminEvents;
        }
    }
}

pub mod faucet {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct FaucetConfig {
        pub amount: U256,
        pub cooldown_secs: u64,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum TokenError {
        Paused,
        ZeroAddress,
        ZeroAmount,
        InsufficientBalance,
        InsufficientAllowance,
        Unauthorized,
        Overflow,
        FaucetDisabled,
        FaucetCooldown { next_claim_at: u64 },
    }

    pub trait Faucet {
        type Env: sails_rs::client::GearEnv;
        fn claim(&mut self) -> sails_rs::client::PendingCall<io::Claim, Self::Env>;
        fn config(&self) -> sails_rs::client::PendingCall<io::Config, Self::Env>;
        fn next_claim_at(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::NextClaimAt, Self::Env>;
    }

    pub struct FaucetImpl;

    impl sails_rs::client::Identifiable for FaucetImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([239, 94, 202, 216, 207, 14, 211, 66]);
    }

    impl<E: sails_rs::client::GearEnv> Faucet for sails_rs::client::Service<FaucetImpl, E> {
        type Env = E;
        fn claim(&mut self) -> sails_rs::client::PendingCall<io::Claim, Self::Env> {
            self.pending_call(())
        }
        fn config(&self) -> sails_rs::client::PendingCall<io::Config, Self::Env> {
            self.pending_call(())
        }
        fn next_claim_at(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::NextClaimAt, Self::Env> {
            self.pending_call((account,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Claim () -> super::Result<U256, super::TokenError, >, 0, <super::FaucetImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Config () -> super::FaucetConfig, 1, <super::FaucetImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(NextClaimAt (account: ActorId) -> u64, 2, <super::FaucetImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum FaucetEvents {
            #[codec(index = 0)]
            Claimed {
                to: ActorId,
                value: U256,
                next_claim_at: u64,
            },
        }

        impl FaucetEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Claimed { .. } => 0,
                }
            }
        }

        impl sails_rs::client::Event for FaucetEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for FaucetEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <FaucetImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for FaucetImpl {
            type Event = FaucetEvents;
        }
    }
}
