// Generated by scripts/gen-clients.sh (cargo sails client-js). Do not edit by hand.
/* eslint-disable */
// @ts-nocheck
import {GearApi, HexString} from "@gear-js/api";
import {ActorId, QueryBuilderWithHeader, TransactionBuilderWithHeader, TypeResolver, ZERO_ADDRESS} from "sails-js";
import {InterfaceId, SailsMessageHeader} from "sails-js/parser";
import {IStructField} from "sails-js/types";

export class DemoToken {
    private _typeResolver: TypeResolver;
    constructor(
        public api: GearApi,
        private _programId?: `0x${string}`,
    ) {
        this._typeResolver = new TypeResolver([]);
    }

    private get registry() {
        return this._typeResolver.registry;
    }

    public get programId(): HexString {
        if (!this._programId) throw new Error("Program ID is not set");
        return this._programId;
    }

    public newCtorFromCode(code: Uint8Array | Buffer | HexString, name: string, $symbol: string, decimals: number, faucet_amount: bigint, faucet_cooldown_secs: number): TransactionBuilderWithHeader<null> {
        const builder = new TransactionBuilderWithHeader<null>(
            this.api,
            this.registry,
            "upload_program",
            SailsMessageHeader.v1(InterfaceId.zero(), 0, 0),
            [name, $symbol, decimals, faucet_amount, faucet_cooldown_secs],
            this._typeResolver.getTypeDeclString({"kind":"tuple","types":["String", "String", "u8", "U256", "u64"]}),
            this._typeResolver.getTypeDeclString("String"),
            code,
        );
        this._programId = builder.programId;
        return builder;
    }

    public newCtorFromCodeId(codeId: `0x${string}`, name: string, $symbol: string, decimals: number, faucet_amount: bigint, faucet_cooldown_secs: number): TransactionBuilderWithHeader<null> {
        const builder = new TransactionBuilderWithHeader<null>(
            this.api,
            this.registry,
            "create_program",
            SailsMessageHeader.v1(InterfaceId.zero(), 0, 0),
            [name, $symbol, decimals, faucet_amount, faucet_cooldown_secs],
            this._typeResolver.getTypeDeclString({"kind":"tuple","types":["String", "String", "u8", "U256", "u64"]}),
            this._typeResolver.getTypeDeclString("String"),
            codeId,
        );
        this._programId = builder.programId;
        return builder;
    }

    public get vft(): Vft {
        return new Vft(this.api, this.programId, 1);
    }

    public get admin(): Admin {
        return new Admin(this.api, this.programId, 2);
    }

    public get faucet(): Faucet {
        return new Faucet(this.api, this.programId, 3);
    }
}

export type TokenError = { Paused: null } | { ZeroAddress: null } | { ZeroAmount: null } | { InsufficientBalance: null } | { InsufficientAllowance: null } | { Unauthorized: null } | { Overflow: null } | { FaucetDisabled: null } | { FaucetCooldown: { next_claim_at: number } };

export class Vft {
    private _typeResolver: TypeResolver;
    constructor(
        private _api: GearApi,
        private _programId: HexString,
        private _routeIdx: number = 0,
    ) {
        this._typeResolver = new TypeResolver([{"name":"TokenError","kind":"enum","variants":[{"name":"Paused","fields":[],"entry_id":0},{"name":"ZeroAddress","fields":[],"entry_id":0},{"name":"ZeroAmount","fields":[],"entry_id":0},{"name":"InsufficientBalance","fields":[],"entry_id":0},{"name":"InsufficientAllowance","fields":[],"entry_id":0},{"name":"Unauthorized","fields":[],"entry_id":0},{"name":"Overflow","fields":[],"entry_id":0},{"name":"FaucetDisabled","fields":[],"entry_id":0},{"name":"FaucetCooldown","fields":[{"name":"next_claim_at","type":"u64"}],"entry_id":0}]}]);
    }
    private get registry() {
        return this._typeResolver.registry;
    }
    public get interfaceId(): InterfaceId {
        return InterfaceId.from("0x694cb0ae4266d779");
    }
    public allowance(owner: ActorId, spender: ActorId): QueryBuilderWithHeader<bigint> {
        return new QueryBuilderWithHeader<bigint>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 0, this._routeIdx),
            [owner, spender],
            this._typeResolver.getTypeDeclString({"kind":"tuple","types":["ActorId", "ActorId"]}),
            this._typeResolver.getTypeDeclString("U256"),
        );
    }

    public approve(spender: ActorId, value: bigint): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 1, this._routeIdx),
            [spender, value],
            this._typeResolver.getTypeDeclString({"kind":"tuple","types":["ActorId", "U256"]}),
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public balanceOf(account: ActorId): QueryBuilderWithHeader<bigint> {
        return new QueryBuilderWithHeader<bigint>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 2, this._routeIdx),
            account,
            this._typeResolver.getTypeDeclString("ActorId"),
            this._typeResolver.getTypeDeclString("U256"),
        );
    }

    public decimals(): QueryBuilderWithHeader<number> {
        return new QueryBuilderWithHeader<number>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 3, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString("u8"),
        );
    }

    public name(): QueryBuilderWithHeader<string> {
        return new QueryBuilderWithHeader<string>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 4, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString("String"),
        );
    }

    public $symbol(): QueryBuilderWithHeader<string> {
        return new QueryBuilderWithHeader<string>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 5, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString("String"),
        );
    }

    public totalSupply(): QueryBuilderWithHeader<bigint> {
        return new QueryBuilderWithHeader<bigint>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 6, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString("U256"),
        );
    }

    public transfer(to: ActorId, value: bigint): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 7, this._routeIdx),
            [to, value],
            this._typeResolver.getTypeDeclString({"kind":"tuple","types":["ActorId", "U256"]}),
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public transferFrom($from: ActorId, to: ActorId, value: bigint): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 8, this._routeIdx),
            [$from, to, value],
            this._typeResolver.getTypeDeclString({"kind":"tuple","types":["ActorId", "ActorId", "U256"]}),
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public subscribeToApprovalEvent<T = { owner: ActorId; spender: ActorId; value: bigint }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"owner","type":"ActorId"},{"name":"spender","type":"ActorId"},{"name":"value","type":"U256"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 0) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }

    public subscribeToTransferEvent<T = { $from: ActorId; to: ActorId; value: bigint }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"from","type":"ActorId"},{"name":"to","type":"ActorId"},{"name":"value","type":"U256"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 1) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }
}


export class Admin {
    private _typeResolver: TypeResolver;
    constructor(
        private _api: GearApi,
        private _programId: HexString,
        private _routeIdx: number = 0,
    ) {
        this._typeResolver = new TypeResolver([{"name":"TokenError","kind":"enum","variants":[{"name":"Paused","fields":[],"entry_id":0},{"name":"ZeroAddress","fields":[],"entry_id":0},{"name":"ZeroAmount","fields":[],"entry_id":0},{"name":"InsufficientBalance","fields":[],"entry_id":0},{"name":"InsufficientAllowance","fields":[],"entry_id":0},{"name":"Unauthorized","fields":[],"entry_id":0},{"name":"Overflow","fields":[],"entry_id":0},{"name":"FaucetDisabled","fields":[],"entry_id":0},{"name":"FaucetCooldown","fields":[{"name":"next_claim_at","type":"u64"}],"entry_id":0}]}]);
    }
    private get registry() {
        return this._typeResolver.registry;
    }
    public get interfaceId(): InterfaceId {
        return InterfaceId.from("0x35c2d98dbcb918ed");
    }
    public adminAccount(): QueryBuilderWithHeader<ActorId> {
        return new QueryBuilderWithHeader<ActorId>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 0, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString("ActorId"),
        );
    }

    public burn($from: ActorId, value: bigint): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 1, this._routeIdx),
            [$from, value],
            this._typeResolver.getTypeDeclString({"kind":"tuple","types":["ActorId", "U256"]}),
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public grantMinter(account: ActorId): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 2, this._routeIdx),
            account,
            this._typeResolver.getTypeDeclString("ActorId"),
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public isMinter(account: ActorId): QueryBuilderWithHeader<boolean> {
        return new QueryBuilderWithHeader<boolean>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 3, this._routeIdx),
            account,
            this._typeResolver.getTypeDeclString("ActorId"),
            this._typeResolver.getTypeDeclString("bool"),
        );
    }

    public isPaused(): QueryBuilderWithHeader<boolean> {
        return new QueryBuilderWithHeader<boolean>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 4, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString("bool"),
        );
    }

    public mint(to: ActorId, value: bigint): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 5, this._routeIdx),
            [to, value],
            this._typeResolver.getTypeDeclString({"kind":"tuple","types":["ActorId", "U256"]}),
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public minters(): QueryBuilderWithHeader<ActorId[]> {
        return new QueryBuilderWithHeader<ActorId[]>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 6, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString({"kind":"slice","item":"ActorId"}),
        );
    }

    public pause(): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 7, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public resume(): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 8, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public revokeMinter(account: ActorId): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 9, this._routeIdx),
            account,
            this._typeResolver.getTypeDeclString("ActorId"),
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public setFaucet(amount: bigint, cooldown_secs: number): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 10, this._routeIdx),
            [amount, cooldown_secs],
            this._typeResolver.getTypeDeclString({"kind":"tuple","types":["U256", "u64"]}),
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public transferAdmin(to: ActorId): TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: boolean } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 11, this._routeIdx),
            to,
            this._typeResolver.getTypeDeclString("ActorId"),
            this._typeResolver.getTypeDeclString("bool"),
            this._programId,
        );
    }

    public subscribeToAdminTransferredEvent<T = { $from: ActorId; to: ActorId }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"from","type":"ActorId"},{"name":"to","type":"ActorId"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 0) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }

    public subscribeToBurnedEvent<T = { $from: ActorId; value: bigint }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"from","type":"ActorId"},{"name":"value","type":"U256"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 1) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }

    public subscribeToFaucetConfiguredEvent<T = { amount: bigint; cooldown_secs: number }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"amount","type":"U256"},{"name":"cooldown_secs","type":"u64"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 2) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }

    public subscribeToMintedEvent<T = { to: ActorId; value: bigint }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"to","type":"ActorId"},{"name":"value","type":"U256"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 3) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }

    public subscribeToMinterGrantedEvent<T = { account: ActorId }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"account","type":"ActorId"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 4) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }

    public subscribeToMinterRevokedEvent<T = { account: ActorId }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"account","type":"ActorId"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 5) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }

    public subscribeToPausedEvent<T = { by: ActorId }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"by","type":"ActorId"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 6) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }

    public subscribeToResumedEvent<T = { by: ActorId }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"by","type":"ActorId"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 7) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }
}

export interface FaucetConfig { amount: bigint; cooldown_secs: number }


export class Faucet {
    private _typeResolver: TypeResolver;
    constructor(
        private _api: GearApi,
        private _programId: HexString,
        private _routeIdx: number = 0,
    ) {
        this._typeResolver = new TypeResolver([{"name":"FaucetConfig","kind":"struct","fields":[{"name":"amount","type":"U256"},{"name":"cooldown_secs","type":"u64"}]}, {"name":"TokenError","kind":"enum","variants":[{"name":"Paused","fields":[],"entry_id":0},{"name":"ZeroAddress","fields":[],"entry_id":0},{"name":"ZeroAmount","fields":[],"entry_id":0},{"name":"InsufficientBalance","fields":[],"entry_id":0},{"name":"InsufficientAllowance","fields":[],"entry_id":0},{"name":"Unauthorized","fields":[],"entry_id":0},{"name":"Overflow","fields":[],"entry_id":0},{"name":"FaucetDisabled","fields":[],"entry_id":0},{"name":"FaucetCooldown","fields":[{"name":"next_claim_at","type":"u64"}],"entry_id":0}]}]);
    }
    private get registry() {
        return this._typeResolver.registry;
    }
    public get interfaceId(): InterfaceId {
        return InterfaceId.from("0xef5ecad8cf0ed342");
    }
    public claim(): TransactionBuilderWithHeader<{ ok: bigint } | { err: TokenError }> {
        return new TransactionBuilderWithHeader<{ ok: bigint } | { err: TokenError }>(
            this._api,
            this.registry,
            "send_message",
            SailsMessageHeader.v1(this.interfaceId, 0, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString({"kind":"named","name":"Result","generics":["U256",{"kind":"named","name":"TokenError"}]}),
            this._programId,
        );
    }

    public config(): QueryBuilderWithHeader<FaucetConfig> {
        return new QueryBuilderWithHeader<FaucetConfig>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 1, this._routeIdx),
            null,
            null,
            this._typeResolver.getTypeDeclString({"kind":"named","name":"FaucetConfig"}),
        );
    }

    public nextClaimAt(account: ActorId): QueryBuilderWithHeader<number> {
        return new QueryBuilderWithHeader<number>(
            this._api,
            this.registry,
            this._programId,
            SailsMessageHeader.v1(this.interfaceId, 2, this._routeIdx),
            account,
            this._typeResolver.getTypeDeclString("ActorId"),
            this._typeResolver.getTypeDeclString("u64"),
        );
    }

    public subscribeToClaimedEvent<T = { to: ActorId; value: bigint; next_claim_at: number }>(callback: (eventData: T) => void | Promise<void>): Promise<() => void> {
        const interfaceIdu64 = this.interfaceId.asU64();
        const eventFields = {"fields":[{"name":"to","type":"ActorId"},{"name":"value","type":"U256"},{"name":"next_claim_at","type":"u64"}]}.fields as IStructField[];
        const typeStr = this._typeResolver.getStructDef(eventFields, {}, true);
        return this._api.gearEvents.subscribeToGearEvent("UserMessageSent", ({ data: { message } }) => {
            if (!message.source.eq(this._programId)) return;
            if (!message.destination.eq(ZERO_ADDRESS)) return;

            const { ok, header } = SailsMessageHeader.tryFromBytes(message.payload);
            if (ok && header.interfaceId.asU64() === interfaceIdu64 && header.entryId === 0) {
                callback(this.registry.createType(`([u8; 16], ${typeStr})`, message.payload)[1].toJSON() as T);
            }
        });
    }
}
