// Post-process a `cargo sails client-js` output so it compiles under the app's strict TS config:
// prepend a header, and drop duplicate top-level type declarations (the generator repeats
// per-service types such as `TokenError` once per service).
import { readFileSync, writeFileSync } from 'node:fs';

const file = process.argv[2];
let src = readFileSync(file, 'utf8');
src = src.replace(/^\/\/ Generated by scripts[\s\S]*?\/\* eslint-disable \*\/\n\/\/ @ts-nocheck\n/, '');

const seen = new Set();
const out = [];
const lines = src.split('\n');
for (let i = 0; i < lines.length; i++) {
  const m = /^export (?:type|interface) (\w+)\b/.exec(lines[i]);
  if (!m) { out.push(lines[i]); continue; }
  // find the end of this declaration: a line that ends the statement at top level
  let j = i;
  let depth = 0;
  let ended = false;
  for (; j < lines.length; j++) {
    for (const ch of lines[j]) { if (ch === '{') depth++; else if (ch === '}') depth--; }
    if (depth <= 0 && (/;\s*$/.test(lines[j]) || /}\s*$/.test(lines[j]))) { ended = true; break; }
  }
  if (!ended) j = i;
  const block = lines.slice(i, j + 1);
  if (seen.has(m[1])) { i = j; continue; }
  seen.add(m[1]);
  out.push(...block);
  i = j;
}
let text = out.join('\n');

// A service named like the program (e.g. service `Vault` in program `Vault`) is emitted as a
// second `export class Vault`, which shadows the program class for type checking. Rename the
// service class to `<Name>Service` and point the program's getter at it.
const classNames = [...text.matchAll(/^export class (\w+) \{/gm)].map((m) => m[1]);
const programClass = classNames[0];
if (classNames.filter((n) => n === programClass).length > 1) {
  const svc = `${programClass}Service`;
  let seen = 0;
  text = text.replace(/^export class (\w+) \{/gm, (m, name) => {
    if (name !== programClass) return m;
    seen += 1;
    return seen === 1 ? m : `export class ${svc} {`;
  });
  const lower = programClass.charAt(0).toLowerCase() + programClass.slice(1);
  text = text.replace(new RegExp(`public get ${lower}\\(\\): ${programClass} \\{\\n(\\s+)return new ${programClass}\\(`), `public get ${lower}(): ${svc} {\n$1return new ${svc}(`);
}

const header = '// Generated by scripts/gen-clients.sh (cargo sails client-js). Do not edit by hand.\n/* eslint-disable */\n// @ts-nocheck\n';
writeFileSync(file, header + text);
