// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct VaraPoolClientProgram;

impl VaraPoolClientProgram {
    pub const ROUTE_ID_VFT: u8 = 1;
    pub const ROUTE_ID_POOL: u8 = 2;
}

impl sails_rs::client::Program for VaraPoolClientProgram {}

pub trait VaraPoolClient {
    type Env: sails_rs::client::GearEnv;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env>;
    fn pool(&self) -> sails_rs::client::Service<pool::PoolImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> VaraPoolClient
    for sails_rs::client::Actor<VaraPoolClientProgram, E>
{
    type Env = E;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env> {
        self.service(VaraPoolClientProgram::ROUTE_ID_VFT)
    }
    fn pool(&self) -> sails_rs::client::Service<pool::PoolImpl, Self::Env> {
        self.service(VaraPoolClientProgram::ROUTE_ID_POOL)
    }
}
pub trait VaraPoolClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
        apy_bps: u32,
        instant_fee_bps: u32,
        unbond_period_secs: u64,
        initial_rate: U256,
    ) -> sails_rs::client::PendingCtor<VaraPoolClientProgram, io::New, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> VaraPoolClientCtors
    for sails_rs::client::Deployment<VaraPoolClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
        apy_bps: u32,
        instant_fee_bps: u32,
        unbond_period_secs: u64,
        initial_rate: U256,
    ) -> sails_rs::client::PendingCtor<VaraPoolClientProgram, io::New, Self::Env> {
        self.pending_ctor((
            name,
            symbol,
            decimals,
            apy_bps,
            instant_fee_bps,
            unbond_period_secs,
            initial_rate,
        ))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (name: String, symbol: String, decimals: u8, apy_bps: u32, instant_fee_bps: u32, unbond_period_secs: u64, initial_rate: U256) -> (), 0);
}

pub mod vft {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum PoolError {
        Paused,
        ZeroAddress,
        ZeroAmount,
        BelowMinimum {
            min: U256,
        },
        InsufficientShares,
        InsufficientBalance,
        InsufficientAllowance,
        /// The pool's VARA reserve cannot cover this payout yet; nothing changed.
        InsufficientReserve {
            available: U256,
        },
        Unauthorized,
        Overflow,
        BadConfig,
        UnbondNotFound,
        UnbondNotReady {
            claimable_at: u64,
        },
        /// The runtime refused the value transfer; the position was restored.
        TransferFailed(String),
        /// The session key acting for the owner has expired.
        SessionExpired,
        /// The session key acting for the owner may not perform this action.
        SessionNotAllowed,
        /// Session key, duration or action list is invalid.
        BadSession,
    }

    pub trait Vft {
        type Env: sails_rs::client::GearEnv;
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env>;
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env>;
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env>;
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
    }

    pub struct VftImpl;

    impl sails_rs::client::Identifiable for VftImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([114, 118, 6, 148, 232, 72, 176, 231]);
    }

    impl<E: sails_rs::client::GearEnv> Vft for sails_rs::client::Service<VftImpl, E> {
        type Env = E;
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env> {
            self.pending_call((owner, spender))
        }
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((spender, value))
        }
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((account,))
        }
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env> {
            self.pending_call(())
        }
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env> {
            self.pending_call((to, value))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, value))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Allowance (owner: ActorId, spender: ActorId) -> U256, 0, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Approve (spender: ActorId, value: U256) -> bool | super::PoolError, 1, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(BalanceOf (account: ActorId) -> U256, 2, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Decimals () -> u8, 3, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Name () -> String, 4, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Symbol () -> String, 5, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TotalSupply () -> U256, 6, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Transfer (to: ActorId, value: U256) -> bool | super::PoolError, 7, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, value: U256) -> bool | super::PoolError, 8, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum VftEvents {
            #[codec(index = 0)]
            Approval {
                owner: ActorId,
                spender: ActorId,
                value: U256,
            },
            #[codec(index = 1)]
            Transfer {
                from: ActorId,
                to: ActorId,
                value: U256,
            },
        }

        impl VftEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Approval { .. } => 0,
                    Self::Transfer { .. } => 1,
                }
            }
        }

        impl sails_rs::client::Event for VftEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for VftEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for VftImpl {
            type Event = VftEvents;
        }
    }
}

pub mod pool {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum PoolError {
        Paused,
        ZeroAddress,
        ZeroAmount,
        BelowMinimum {
            min: U256,
        },
        InsufficientShares,
        InsufficientBalance,
        InsufficientAllowance,
        /// The pool's VARA reserve cannot cover this payout yet; nothing changed.
        InsufficientReserve {
            available: U256,
        },
        Unauthorized,
        Overflow,
        BadConfig,
        UnbondNotFound,
        UnbondNotReady {
            claimable_at: u64,
        },
        /// The runtime refused the value transfer; the position was restored.
        TransferFailed(String),
        /// The session key acting for the owner has expired.
        SessionExpired,
        /// The session key acting for the owner may not perform this action.
        SessionNotAllowed,
        /// Session key, duration or action list is invalid.
        BadSession,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct PoolInfo {
        pub admin: ActorId,
        pub name: String,
        pub symbol: String,
        pub decimals: u8,
        /// VARA per kVARA scaled by 1e18, projected to now.
        pub rate: U256,
        pub apy_bps: u32,
        pub instant_fee_bps: u32,
        pub unbond_period_secs: u64,
        pub total_shares: U256,
        /// VARA owed to share holders at the projected rate.
        pub total_assets: U256,
        /// VARA the pool physically holds for payouts (stakes plus funded rewards).
        pub reserve: U256,
        pub fees_accrued: U256,
        pub unbonding_total: U256,
        pub min_stake: U256,
        pub paused: bool,
        pub last_accrual_at: u64,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Position {
        pub shares: U256,
        pub assets: U256,
    }
    /// A session key registered by an owner: messages signed by `key` act for the owner until
    /// `expires_at`. Payouts always go to the owner, never to the key.
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Session {
        pub key: ActorId,
        pub expires_at: u64,
        pub actions: Vec<SessionAction>,
    }
    /// Actions a session key may perform for its owner.
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum SessionAction {
        Stake,
        Unstake,
        Unbond,
        Claim,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Unbond {
        pub id: u64,
        pub shares: U256,
        pub assets: U256,
        pub requested_at: u64,
        pub claimable_at: u64,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct UnstakePreview {
        pub assets: U256,
        pub fee: U256,
        pub net: U256,
    }

    pub trait Pool {
        type Env: sails_rs::client::GearEnv;
        fn accrue(&mut self) -> sails_rs::client::PendingCall<io::Accrue, Self::Env>;
        fn claim(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env>;
        fn collect_fees(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::CollectFees, Self::Env>;
        fn create_session(
            &mut self,
            key: ActorId,
            duration_secs: u64,
            actions: Vec<SessionAction>,
        ) -> sails_rs::client::PendingCall<io::CreateSession, Self::Env>;
        fn fund_rewards(&mut self) -> sails_rs::client::PendingCall<io::FundRewards, Self::Env>;
        fn info(&self) -> sails_rs::client::PendingCall<io::Info, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn position(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::Position, Self::Env>;
        fn preview_stake(
            &self,
            assets: U256,
        ) -> sails_rs::client::PendingCall<io::PreviewStake, Self::Env>;
        fn preview_unstake(
            &self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::PreviewUnstake, Self::Env>;
        fn rate(&self) -> sails_rs::client::PendingCall<io::Rate, Self::Env>;
        fn request_unbond(
            &mut self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::RequestUnbond, Self::Env>;
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env>;
        fn revoke_session(&mut self)
        -> sails_rs::client::PendingCall<io::RevokeSession, Self::Env>;
        fn session(&self, owner: ActorId) -> sails_rs::client::PendingCall<io::Session, Self::Env>;
        fn session_owner(
            &self,
            key: ActorId,
        ) -> sails_rs::client::PendingCall<io::SessionOwner, Self::Env>;
        fn set_config(
            &mut self,
            apy_bps: u32,
            instant_fee_bps: u32,
            unbond_period_secs: u64,
        ) -> sails_rs::client::PendingCall<io::SetConfig, Self::Env>;
        fn stake(&mut self) -> sails_rs::client::PendingCall<io::Stake, Self::Env>;
        fn transfer_admin(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env>;
        fn unbonds(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::Unbonds, Self::Env>;
        fn unstake(
            &mut self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::Unstake, Self::Env>;
    }

    pub struct PoolImpl;

    impl sails_rs::client::Identifiable for PoolImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([211, 50, 255, 16, 94, 50, 244, 113]);
    }

    impl<E: sails_rs::client::GearEnv> Pool for sails_rs::client::Service<PoolImpl, E> {
        type Env = E;
        fn accrue(&mut self) -> sails_rs::client::PendingCall<io::Accrue, Self::Env> {
            self.pending_call(())
        }
        fn claim(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env> {
            self.pending_call((id,))
        }
        fn collect_fees(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::CollectFees, Self::Env> {
            self.pending_call((to,))
        }
        fn create_session(
            &mut self,
            key: ActorId,
            duration_secs: u64,
            actions: Vec<SessionAction>,
        ) -> sails_rs::client::PendingCall<io::CreateSession, Self::Env> {
            self.pending_call((key, duration_secs, actions))
        }
        fn fund_rewards(&mut self) -> sails_rs::client::PendingCall<io::FundRewards, Self::Env> {
            self.pending_call(())
        }
        fn info(&self) -> sails_rs::client::PendingCall<io::Info, Self::Env> {
            self.pending_call(())
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn position(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::Position, Self::Env> {
            self.pending_call((account,))
        }
        fn preview_stake(
            &self,
            assets: U256,
        ) -> sails_rs::client::PendingCall<io::PreviewStake, Self::Env> {
            self.pending_call((assets,))
        }
        fn preview_unstake(
            &self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::PreviewUnstake, Self::Env> {
            self.pending_call((shares,))
        }
        fn rate(&self) -> sails_rs::client::PendingCall<io::Rate, Self::Env> {
            self.pending_call(())
        }
        fn request_unbond(
            &mut self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::RequestUnbond, Self::Env> {
            self.pending_call((shares,))
        }
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env> {
            self.pending_call(())
        }
        fn revoke_session(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::RevokeSession, Self::Env> {
            self.pending_call(())
        }
        fn session(&self, owner: ActorId) -> sails_rs::client::PendingCall<io::Session, Self::Env> {
            self.pending_call((owner,))
        }
        fn session_owner(
            &self,
            key: ActorId,
        ) -> sails_rs::client::PendingCall<io::SessionOwner, Self::Env> {
            self.pending_call((key,))
        }
        fn set_config(
            &mut self,
            apy_bps: u32,
            instant_fee_bps: u32,
            unbond_period_secs: u64,
        ) -> sails_rs::client::PendingCall<io::SetConfig, Self::Env> {
            self.pending_call((apy_bps, instant_fee_bps, unbond_period_secs))
        }
        fn stake(&mut self) -> sails_rs::client::PendingCall<io::Stake, Self::Env> {
            self.pending_call(())
        }
        fn transfer_admin(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env> {
            self.pending_call((to,))
        }
        fn unbonds(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::Unbonds, Self::Env> {
            self.pending_call((account,))
        }
        fn unstake(
            &mut self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::Unstake, Self::Env> {
            self.pending_call((shares,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Accrue () -> U256, 0, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Claim (id: u64) -> super::Result<U256, super::PoolError, >, 1, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CollectFees (to: ActorId) -> super::Result<U256, super::PoolError, >, 2, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CreateSession (key: ActorId, duration_secs: u64, actions: Vec<super::SessionAction>) -> super::Result<super::Session, super::PoolError, >, 3, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(FundRewards () -> super::Result<U256, super::PoolError, >, 4, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Info () -> super::PoolInfo, 5, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Pause () -> super::Result<bool, super::PoolError, >, 6, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Position (account: ActorId) -> super::Position, 7, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PreviewStake (assets: U256) -> U256, 8, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PreviewUnstake (shares: U256) -> super::UnstakePreview, 9, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Rate () -> U256, 10, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RequestUnbond (shares: U256) -> super::Result<super::Unbond, super::PoolError, >, 11, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Resume () -> super::Result<bool, super::PoolError, >, 12, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RevokeSession () -> bool, 13, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Session (owner: ActorId) -> super::Option<super::Session, >, 14, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SessionOwner (key: ActorId) -> super::Option<ActorId, >, 15, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetConfig (apy_bps: u32, instant_fee_bps: u32, unbond_period_secs: u64) -> super::Result<bool, super::PoolError, >, 16, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Stake () -> super::Result<U256, super::PoolError, >, 17, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TransferAdmin (to: ActorId) -> super::Result<bool, super::PoolError, >, 18, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Unbonds (account: ActorId) -> Vec<super::Unbond>, 19, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Unstake (shares: U256) -> super::Result<super::UnstakePreview, super::PoolError, >, 20, <super::PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum PoolEvents {
            #[codec(index = 0)]
            Accrued { rate: U256, total_assets: U256 },
            #[codec(index = 1)]
            AdminTransferred { from: ActorId, to: ActorId },
            #[codec(index = 2)]
            Claimed {
                owner: ActorId,
                id: u64,
                assets: U256,
            },
            #[codec(index = 3)]
            ConfigChanged {
                apy_bps: u32,
                instant_fee_bps: u32,
                unbond_period_secs: u64,
            },
            #[codec(index = 4)]
            FeesCollected { to: ActorId, assets: U256 },
            #[codec(index = 5)]
            Paused { by: ActorId },
            #[codec(index = 6)]
            Resumed { by: ActorId },
            #[codec(index = 7)]
            RewardsFunded {
                from: ActorId,
                assets: U256,
                reserve: U256,
            },
            #[codec(index = 8)]
            SessionCreated {
                owner: ActorId,
                key: ActorId,
                expires_at: u64,
            },
            #[codec(index = 9)]
            SessionRevoked { owner: ActorId },
            #[codec(index = 10)]
            Staked {
                owner: ActorId,
                assets: U256,
                shares: U256,
                rate: U256,
            },
            #[codec(index = 11)]
            UnbondRequested {
                owner: ActorId,
                id: u64,
                shares: U256,
                assets: U256,
                claimable_at: u64,
            },
            #[codec(index = 12)]
            Unstaked {
                owner: ActorId,
                shares: U256,
                assets: U256,
                fee: U256,
                rate: U256,
            },
        }

        impl PoolEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Accrued { .. } => 0,
                    Self::AdminTransferred { .. } => 1,
                    Self::Claimed { .. } => 2,
                    Self::ConfigChanged { .. } => 3,
                    Self::FeesCollected { .. } => 4,
                    Self::Paused { .. } => 5,
                    Self::Resumed { .. } => 6,
                    Self::RewardsFunded { .. } => 7,
                    Self::SessionCreated { .. } => 8,
                    Self::SessionRevoked { .. } => 9,
                    Self::Staked { .. } => 10,
                    Self::UnbondRequested { .. } => 11,
                    Self::Unstaked { .. } => 12,
                }
            }
        }

        impl sails_rs::client::Event for PoolEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for PoolEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <PoolImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for PoolImpl {
            type Event = PoolEvents;
        }
    }
}
