// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct VaultClientProgram;

impl VaultClientProgram {
    pub const ROUTE_ID_VFT: u8 = 1;
    pub const ROUTE_ID_VAULT: u8 = 2;
}

impl sails_rs::client::Program for VaultClientProgram {}

pub trait VaultClient {
    type Env: sails_rs::client::GearEnv;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env>;
    fn vault(&self) -> sails_rs::client::Service<vault::VaultImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> VaultClient for sails_rs::client::Actor<VaultClientProgram, E> {
    type Env = E;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env> {
        self.service(VaultClientProgram::ROUTE_ID_VFT)
    }
    fn vault(&self) -> sails_rs::client::Service<vault::VaultImpl, Self::Env> {
        self.service(VaultClientProgram::ROUTE_ID_VAULT)
    }
}
pub trait VaultClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        underlying: ActorId,
        name: String,
        symbol: String,
        decimals: u8,
        instant_fee_bps: u32,
        unbond_period_secs: u64,
        vesting_period_secs: u64,
        initial_rate: U256,
    ) -> sails_rs::client::PendingCtor<VaultClientProgram, io::New, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> VaultClientCtors
    for sails_rs::client::Deployment<VaultClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        underlying: ActorId,
        name: String,
        symbol: String,
        decimals: u8,
        instant_fee_bps: u32,
        unbond_period_secs: u64,
        vesting_period_secs: u64,
        initial_rate: U256,
    ) -> sails_rs::client::PendingCtor<VaultClientProgram, io::New, Self::Env> {
        self.pending_ctor((
            underlying,
            name,
            symbol,
            decimals,
            instant_fee_bps,
            unbond_period_secs,
            vesting_period_secs,
            initial_rate,
        ))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (underlying: ActorId, name: String, symbol: String, decimals: u8, instant_fee_bps: u32, unbond_period_secs: u64, vesting_period_secs: u64, initial_rate: U256) -> (), 0);
}

pub mod vft {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum VaultError {
        Paused,
        ZeroAddress,
        ZeroAmount,
        BelowMinimum {
            min: U256,
        },
        InsufficientShares,
        InsufficientBalance,
        InsufficientAllowance,
        /// The vault's distributable assets cannot cover this payout; nothing changed.
        InsufficientReserve {
            available: U256,
        },
        Unauthorized,
        Overflow,
        BadConfig,
        UnbondNotFound,
        UnbondNotReady {
            claimable_at: u64,
        },
        /// The underlying token rejected the transfer (allowance, balance, paused).
        TokenRejected(String),
        /// The cross-program call failed to complete (timeout, transport, panic).
        TokenCall(String),
        /// The message carried less gas than the async flow needs; nothing was moved.
        NotEnoughGas {
            required: u64,
        },
        /// The session key acting for the owner has expired.
        SessionExpired,
        /// The session key acting for the owner may not perform this action.
        SessionNotAllowed,
        /// Session key, duration or action list is invalid, or no matching proposal exists.
        BadSession,
    }

    pub trait Vft {
        type Env: sails_rs::client::GearEnv;
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env>;
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env>;
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env>;
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
    }

    pub struct VftImpl;

    impl sails_rs::client::Identifiable for VftImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([136, 110, 133, 14, 44, 159, 49, 139]);
    }

    impl<E: sails_rs::client::GearEnv> Vft for sails_rs::client::Service<VftImpl, E> {
        type Env = E;
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env> {
            self.pending_call((owner, spender))
        }
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((spender, value))
        }
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((account,))
        }
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env> {
            self.pending_call(())
        }
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env> {
            self.pending_call((to, value))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, value))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Allowance (owner: ActorId, spender: ActorId) -> U256, 0, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Approve (spender: ActorId, value: U256) -> bool | super::VaultError, 1, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(BalanceOf (account: ActorId) -> U256, 2, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Decimals () -> u8, 3, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Name () -> String, 4, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Symbol () -> String, 5, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TotalSupply () -> U256, 6, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Transfer (to: ActorId, value: U256) -> bool | super::VaultError, 7, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, value: U256) -> bool | super::VaultError, 8, <super::VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum VftEvents {
            #[codec(index = 0)]
            Approval {
                owner: ActorId,
                spender: ActorId,
                value: U256,
            },
            #[codec(index = 1)]
            Transfer {
                from: ActorId,
                to: ActorId,
                value: U256,
            },
        }

        impl VftEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Approval { .. } => 0,
                    Self::Transfer { .. } => 1,
                }
            }
        }

        impl sails_rs::client::Event for VftEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for VftEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <VftImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for VftImpl {
            type Event = VftEvents;
        }
    }
}

pub mod vault {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Position {
        pub shares: U256,
        pub assets: U256,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct RedeemPreview {
        pub assets: U256,
        pub fee: U256,
        pub net: U256,
    }
    /// A session key registered by an owner: messages signed by `key` act for the owner until
    /// `expires_at`. Payouts always go to the owner, never to the key. A session is proposed by
    /// the owner and only takes effect once the key itself accepts it, so nobody can bind an
    /// address they do not control.
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Session {
        pub key: ActorId,
        pub expires_at: u64,
        pub actions: Vec<SessionAction>,
    }
    /// Actions a session key may perform for its owner.
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum SessionAction {
        Deposit,
        Redeem,
        Unbond,
        Claim,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Unbond {
        pub id: u64,
        pub shares: U256,
        pub assets: U256,
        pub requested_at: u64,
        pub claimable_at: u64,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum VaultError {
        Paused,
        ZeroAddress,
        ZeroAmount,
        BelowMinimum {
            min: U256,
        },
        InsufficientShares,
        InsufficientBalance,
        InsufficientAllowance,
        /// The vault's distributable assets cannot cover this payout; nothing changed.
        InsufficientReserve {
            available: U256,
        },
        Unauthorized,
        Overflow,
        BadConfig,
        UnbondNotFound,
        UnbondNotReady {
            claimable_at: u64,
        },
        /// The underlying token rejected the transfer (allowance, balance, paused).
        TokenRejected(String),
        /// The cross-program call failed to complete (timeout, transport, panic).
        TokenCall(String),
        /// The message carried less gas than the async flow needs; nothing was moved.
        NotEnoughGas {
            required: u64,
        },
        /// The session key acting for the owner has expired.
        SessionExpired,
        /// The session key acting for the owner may not perform this action.
        SessionNotAllowed,
        /// Session key, duration or action list is invalid, or no matching proposal exists.
        BadSession,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct VaultInfo {
        pub underlying: ActorId,
        pub admin: ActorId,
        pub name: String,
        pub symbol: String,
        pub decimals: u8,
        /// Assets per share scaled by 1e18: distributable assets over shares, now.
        pub rate: U256,
        /// Annualised release rate of the rewards currently vesting, over distributable assets.
        /// Zero once the current tranche has fully vested.
        pub apy_bps: u32,
        pub instant_fee_bps: u32,
        pub unbond_period_secs: u64,
        pub vesting_period_secs: u64,
        pub total_shares: U256,
        /// Assets owed to share holders: the distributable amount.
        pub total_assets: U256,
        /// Underlying the vault physically holds (deposits, rewards, fees, unbonds).
        pub holdings: U256,
        /// Holdings minus fees, unbonds and rewards still vesting.
        pub distributable: U256,
        /// Rewards not yet released.
        pub locked_rewards: U256,
        /// When the current tranche is fully vested (0 when nothing is vesting).
        pub vesting_ends_at: u64,
        pub fees_accrued: U256,
        pub unbonding_total: U256,
        pub min_deposit: U256,
        pub paused: bool,
    }

    pub trait Vault {
        type Env: sails_rs::client::GearEnv;
        fn accept_session(
            &mut self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::AcceptSession, Self::Env>;
        fn claim(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env>;
        fn collect_fees(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::CollectFees, Self::Env>;
        fn create_session(
            &mut self,
            key: ActorId,
            duration_secs: u64,
            actions: Vec<SessionAction>,
        ) -> sails_rs::client::PendingCall<io::CreateSession, Self::Env>;
        fn deposit(
            &mut self,
            assets: U256,
        ) -> sails_rs::client::PendingCall<io::Deposit, Self::Env>;
        fn fund_rewards(
            &mut self,
            assets: U256,
        ) -> sails_rs::client::PendingCall<io::FundRewards, Self::Env>;
        fn info(&self) -> sails_rs::client::PendingCall<io::Info, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn pending_session(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::PendingSession, Self::Env>;
        fn position(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::Position, Self::Env>;
        fn preview_deposit(
            &self,
            assets: U256,
        ) -> sails_rs::client::PendingCall<io::PreviewDeposit, Self::Env>;
        fn preview_redeem(
            &self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::PreviewRedeem, Self::Env>;
        fn rate(&self) -> sails_rs::client::PendingCall<io::Rate, Self::Env>;
        fn redeem(&mut self, shares: U256) -> sails_rs::client::PendingCall<io::Redeem, Self::Env>;
        fn request_unbond(
            &mut self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::RequestUnbond, Self::Env>;
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env>;
        fn revoke_session(&mut self)
        -> sails_rs::client::PendingCall<io::RevokeSession, Self::Env>;
        fn session(&self, owner: ActorId) -> sails_rs::client::PendingCall<io::Session, Self::Env>;
        fn session_owner(
            &self,
            key: ActorId,
        ) -> sails_rs::client::PendingCall<io::SessionOwner, Self::Env>;
        fn set_config(
            &mut self,
            instant_fee_bps: u32,
            unbond_period_secs: u64,
            vesting_period_secs: u64,
        ) -> sails_rs::client::PendingCall<io::SetConfig, Self::Env>;
        fn transfer_admin(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env>;
        fn unbonds(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::Unbonds, Self::Env>;
    }

    pub struct VaultImpl;

    impl sails_rs::client::Identifiable for VaultImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([30, 211, 98, 65, 146, 28, 254, 57]);
    }

    impl<E: sails_rs::client::GearEnv> Vault for sails_rs::client::Service<VaultImpl, E> {
        type Env = E;
        fn accept_session(
            &mut self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::AcceptSession, Self::Env> {
            self.pending_call((owner,))
        }
        fn claim(&mut self, id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env> {
            self.pending_call((id,))
        }
        fn collect_fees(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::CollectFees, Self::Env> {
            self.pending_call((to,))
        }
        fn create_session(
            &mut self,
            key: ActorId,
            duration_secs: u64,
            actions: Vec<SessionAction>,
        ) -> sails_rs::client::PendingCall<io::CreateSession, Self::Env> {
            self.pending_call((key, duration_secs, actions))
        }
        fn deposit(
            &mut self,
            assets: U256,
        ) -> sails_rs::client::PendingCall<io::Deposit, Self::Env> {
            self.pending_call((assets,))
        }
        fn fund_rewards(
            &mut self,
            assets: U256,
        ) -> sails_rs::client::PendingCall<io::FundRewards, Self::Env> {
            self.pending_call((assets,))
        }
        fn info(&self) -> sails_rs::client::PendingCall<io::Info, Self::Env> {
            self.pending_call(())
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn pending_session(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::PendingSession, Self::Env> {
            self.pending_call((owner,))
        }
        fn position(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::Position, Self::Env> {
            self.pending_call((account,))
        }
        fn preview_deposit(
            &self,
            assets: U256,
        ) -> sails_rs::client::PendingCall<io::PreviewDeposit, Self::Env> {
            self.pending_call((assets,))
        }
        fn preview_redeem(
            &self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::PreviewRedeem, Self::Env> {
            self.pending_call((shares,))
        }
        fn rate(&self) -> sails_rs::client::PendingCall<io::Rate, Self::Env> {
            self.pending_call(())
        }
        fn redeem(&mut self, shares: U256) -> sails_rs::client::PendingCall<io::Redeem, Self::Env> {
            self.pending_call((shares,))
        }
        fn request_unbond(
            &mut self,
            shares: U256,
        ) -> sails_rs::client::PendingCall<io::RequestUnbond, Self::Env> {
            self.pending_call((shares,))
        }
        fn resume(&mut self) -> sails_rs::client::PendingCall<io::Resume, Self::Env> {
            self.pending_call(())
        }
        fn revoke_session(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::RevokeSession, Self::Env> {
            self.pending_call(())
        }
        fn session(&self, owner: ActorId) -> sails_rs::client::PendingCall<io::Session, Self::Env> {
            self.pending_call((owner,))
        }
        fn session_owner(
            &self,
            key: ActorId,
        ) -> sails_rs::client::PendingCall<io::SessionOwner, Self::Env> {
            self.pending_call((key,))
        }
        fn set_config(
            &mut self,
            instant_fee_bps: u32,
            unbond_period_secs: u64,
            vesting_period_secs: u64,
        ) -> sails_rs::client::PendingCall<io::SetConfig, Self::Env> {
            self.pending_call((instant_fee_bps, unbond_period_secs, vesting_period_secs))
        }
        fn transfer_admin(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env> {
            self.pending_call((to,))
        }
        fn unbonds(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::Unbonds, Self::Env> {
            self.pending_call((account,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AcceptSession (owner: ActorId) -> super::Result<super::Session, super::VaultError, >, 0, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Claim (id: u64) -> super::Result<U256, super::VaultError, >, 1, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CollectFees (to: ActorId) -> super::Result<U256, super::VaultError, >, 2, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CreateSession (key: ActorId, duration_secs: u64, actions: Vec<super::SessionAction>) -> super::Result<super::Session, super::VaultError, >, 3, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Deposit (assets: U256) -> super::Result<U256, super::VaultError, >, 4, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(FundRewards (assets: U256) -> super::Result<U256, super::VaultError, >, 5, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Info () -> super::VaultInfo, 6, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Pause () -> super::Result<bool, super::VaultError, >, 7, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PendingSession (owner: ActorId) -> super::Option<super::Session, >, 8, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Position (account: ActorId) -> super::Position, 9, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PreviewDeposit (assets: U256) -> U256, 10, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PreviewRedeem (shares: U256) -> super::RedeemPreview, 11, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Rate () -> U256, 12, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Redeem (shares: U256) -> super::Result<super::RedeemPreview, super::VaultError, >, 13, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RequestUnbond (shares: U256) -> super::Result<super::Unbond, super::VaultError, >, 14, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Resume () -> super::Result<bool, super::VaultError, >, 15, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RevokeSession () -> bool, 16, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Session (owner: ActorId) -> super::Option<super::Session, >, 17, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SessionOwner (key: ActorId) -> super::Option<ActorId, >, 18, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetConfig (instant_fee_bps: u32, unbond_period_secs: u64, vesting_period_secs: u64) -> super::Result<bool, super::VaultError, >, 19, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TransferAdmin (to: ActorId) -> super::Result<bool, super::VaultError, >, 20, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Unbonds (account: ActorId) -> Vec<super::Unbond>, 21, <super::VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum VaultEvents {
            #[codec(index = 0)]
            AdminTransferred { from: ActorId, to: ActorId },
            #[codec(index = 1)]
            Claimed {
                owner: ActorId,
                id: u64,
                assets: U256,
            },
            #[codec(index = 2)]
            ConfigChanged {
                instant_fee_bps: u32,
                unbond_period_secs: u64,
                vesting_period_secs: u64,
            },
            #[codec(index = 3)]
            Deposited {
                owner: ActorId,
                assets: U256,
                shares: U256,
                rate: U256,
            },
            #[codec(index = 4)]
            FeesCollected { to: ActorId, assets: U256 },
            #[codec(index = 5)]
            Paused { by: ActorId },
            #[codec(index = 6)]
            Redeemed {
                owner: ActorId,
                shares: U256,
                assets: U256,
                fee: U256,
                rate: U256,
            },
            #[codec(index = 7)]
            Resumed { by: ActorId },
            #[codec(index = 8)]
            RewardsFunded {
                from: ActorId,
                assets: U256,
                holdings: U256,
                vesting_ends_at: u64,
            },
            #[codec(index = 9)]
            SessionAccepted {
                owner: ActorId,
                key: ActorId,
                expires_at: u64,
            },
            #[codec(index = 10)]
            SessionProposed {
                owner: ActorId,
                key: ActorId,
                expires_at: u64,
            },
            #[codec(index = 11)]
            SessionRevoked { owner: ActorId },
            #[codec(index = 12)]
            UnbondRequested {
                owner: ActorId,
                id: u64,
                shares: U256,
                assets: U256,
                claimable_at: u64,
            },
        }

        impl VaultEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::AdminTransferred { .. } => 0,
                    Self::Claimed { .. } => 1,
                    Self::ConfigChanged { .. } => 2,
                    Self::Deposited { .. } => 3,
                    Self::FeesCollected { .. } => 4,
                    Self::Paused { .. } => 5,
                    Self::Redeemed { .. } => 6,
                    Self::Resumed { .. } => 7,
                    Self::RewardsFunded { .. } => 8,
                    Self::SessionAccepted { .. } => 9,
                    Self::SessionProposed { .. } => 10,
                    Self::SessionRevoked { .. } => 11,
                    Self::UnbondRequested { .. } => 12,
                }
            }
        }

        impl sails_rs::client::Event for VaultEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for VaultEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <VaultImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for VaultImpl {
            type Event = VaultEvents;
        }
    }
}
