[package]
name = "vara-pool"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Package allowing to build WASM binary for the program and IDL file for it"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
sails-rs.workspace = true
vara-pool-app.workspace = true

[dev-dependencies]
sails-rs = { workspace = true, features = ["gtest"] }
tokio = { workspace = true, features = ["rt", "macros"] }
vara-pool-app.workspace = true
vara-pool-client.workspace = true

[build-dependencies]
sails-rs = { workspace = true, features = ["build"] }
vara-pool-app.workspace = true

[workspace]
resolver = "3"
members = ["app", "client"]

[workspace.package]
version = "0.1.0"
authors = ["Vale Protocol"]
edition = "2024"
rust-version = "1.91"
repository = "https://github.com/Adityaakr/vara-pool"
license = "MIT"
keywords = ["gear", "sails", "smart-contracts", "wasm", "no-std"]
categories = ["cryptography::cryptocurrencies", "no-std", "wasm"]

[workspace.dependencies]
sails-rs = "1.0.1"
tokio = "1.50.0"
vara-pool-app = { version = "0.1.0", path = "app" }
vara-pool-client = { version = "0.1.0", path = "client" }
